=== BackupTheBerlios/osinfo-svn/trunk/osinfo/html/dtd/osinfo.dtd
<!ELEMENT osinfo (script|
                  computer|
                  scanning|
                  system|
                  distribution|
                  kernel|
                  processor|
                  system_ram_memory|
                  system_memory|
                  hard_drive_configuration|
                  network_information|
                  wlan_information|
                  dmi_information|
                  applications|
                  terminal_info|
                  devices|
                  enhancements|
                  cd_dvd_drives|
                  users|
                  services|
                  battery|
                  oem_information)*>


<!ELEMENT script EMPTY>
<!ATTLIST script version CDATA #REQUIRED>

<!ELEMENT computer EMPTY>
<!ATTLIST computer profile  CDATA #REQUIRED
                   hostname CDATA #REQUIRED
                   domain   CDATA #REQUIRED
                   os       CDATA #REQUIRED
                   cpu      CDATA #REQUIRED>

<!ELEMENT scanning EMPTY>
<!ATTLIST scanning date CDATA #REQUIRED>




<!ELEMENT attribute (description|value)*>
<!ATTLIST attribute name CDATA #REQUIRED
                    code CDATA #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT value (#PCDATA)>


<!ELEMENT system (attribute+)>
<!ELEMENT distribution (attribute+)>
<!ELEMENT kernel (attribute+)>
<!ELEMENT processor (attribute+)>
<!ELEMENT system_ram_memory (ram+)>
<!ELEMENT system_memory (ram+)>
<!ELEMENT hard_drive_configuration (drive+)>
<!ELEMENT network_information (computer*)>
<!ELEMENT wlan_information (attribute*)> <!-- UNKNOWN -->
<!ELEMENT dmi_information (bios|
                           system_info|
                           motherboard|
                           chassis)*>
<!ELEMENT applications (attribute+)>
<!ELEMENT terminal_info (attribute+)>
<!ELEMENT devices (motherboard,controllers)>
<!ELEMENT enhancements (attribute+)>
<!ELEMENT cd_dvd_drives (cd_drive)*>
<!ELEMENT users (active_user,wtmp_statistics)>
<!ELEMENT services (value+)>
<!ELEMENT battery (attribute*)> <!-- UNKNOWN -->
<!ELEMENT oem_information (attribute+)>



<!-- system_ram_memory, system_memory -->
<!ELEMENT ram (attribute+)>


<!-- hard_drive_configuration -->
<!ELEMENT drive (attribute|partitions)*>
<!ELEMENT partitions (value+)>


<!-- network_information -->
<!-- <!ELEMENT computer (attribute|iface)*>
<!ATTLIST computer name CDATA #REQUIRED> -->
<!ELEMENT iface (attribute+)>
<!ATTLIST iface name CDATA #REQUIRED>


<!-- dmi_information, devices -->
<!ELEMENT motherboard (attribute+)>


<!-- dmi_information -->
<!ELEMENT bios (attribute+)>
<!ELEMENT system_info (attribute+)>
<!ELEMENT chassis (attribute*)>


<!-- devices -->
<!ELEMENT controllers (attribute+)>


<!-- cd_dvd_drives -->
<!ELEMENT cd_drive (attribute+)>
<!ATTLIST cd_drive name CDATA #REQUIRED>


<!-- users -->
<!ELEMENT active_user (value+)>
<!ATTLIST active_user unixname CDATA #REQUIRED>
<!ELEMENT wtmp_statistics (value+)>

=== BackupTheBerlios/osinfo-svn/trunk/osinfo/debug/osinfo-network.xml
<?xml version="1.0" encoding="ISO8859-1" ?>
<!DOCTYPE osinfo SYSTEM "osinfo.dtd">
<osinfo>
	<network_information>
		<interface name="eth0">
			<attribute name="mac" code="mac_address">
				<value>00:13:8F:5D:61:61</value>
			</attribute>
	
			<attribute name="ipv4" code="ip_address">
				<value>192.168.0.1</value>
			</attribute>
	
			<attribute name="ipv6" code="">
				<value>fe80::213:8fff:fe5d:6161</value>
			</attribute>
	
			<attribute name="nis_domain" code="">
				<value>(none)</value>
			</attribute>
	
			<attribute name="dns_domain" code="domain">
			</attribute>
	
			<attribute name="fqdn" code="fully_qualified_domain_name">
			</attribute>
	
			<attribute name="gateway" code="default_gateway">
				<value>192.168.0.254</value>
			</attribute>
	
			<attribute name="broadcast" code="">
				<value>192.168.0.255</value>
			</attribute>
	
			<attribute name="netmask" code="subnet_mask">
				<value>255.255.255.0</value>
			</attribute>
	
			<attribute name="rx_bytes" code="">
				<value>977197815 (931.9 Mb)</value>
			</attribute>
	
			<attribute name="tx_bytes" code="">
				<value>123397720 (117.6 Mb)</value>
			</attribute>
	
		</interface>
		<interface name="eth1">
			<attribute name="mac" code="mac_address">
			</attribute>
	
			<attribute name="ipv4" code="ip_address">
			</attribute>
	
			<attribute name="ipv6" code="">
			</attribute>
	
			<attribute name="nis_domain" code="">
				<value>(none)</value>
			</attribute>
	
			<attribute name="dns_domain" code="domain">
			</attribute>
	
			<attribute name="fqdn" code="fully_qualified_domain_name">
			</attribute>
	
			<attribute name="gateway" code="default_gateway">
				<value>192.168.0.254</value>
			</attribute>
	
			<attribute name="broadcast" code="">
			</attribute>
	
			<attribute name="netmask" code="subnet_mask">
			</attribute>
	
			<attribute name="rx_bytes" code="">
				<value>0 (0.0 b)</value>
			</attribute>
	
			<attribute name="tx_bytes" code="">
				<value>0 (0.0 b)</value>
			</attribute>
	
		</interface>
		<interface name="wlan">
			<attribute name="associated_essid" code="">
				<value>Openlab</value>
			</attribute>
		</interface>
	</network_information>
</osinfo>
